<a href="https://colab.research.google.com/github/dublino8576/creative-project/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#HOW TO CREATE A NUMPY ARRAY WITH A PYTHON LIST
numbers = [1,2,3,4,5]
print("This is a list: ", numbers)

import numpy as np
array = np.array(numbers)
print("This is an array" ,array)

#the reason array doesnt have commas is that is quicker to do calculations


This is a list:  [1, 2, 3, 4, 5]
This is an array [1 2 3 4 5]


In [4]:
doubled = array * 2
print(doubled)
#much quicker to do it with array since you don't need a for loop or a map

[ 2  4  6  8 10]


In [7]:
#USE BUILT-IN NUMPY METHODS TO MAKE AN ARRAY TOO
zeros = np.zeros((2, 3))
print("Print multidimentional array: 3 zeros in 2 nested arrays", zeros)

ones = np.ones((3))
print("ones", ones)

Print multidimentional array: 3 zeros in 2 nested arrays [[0. 0. 0.]
 [0. 0. 0.]]
ones [1. 1. 1.]


In [10]:
#start point, endpoint, step
range_array = np.arange(0, 10, 2)
print("range: ", range_array)

range:  [0 2 4 6 8]


In [12]:
range_of_9 = np.arange(0, 10, 1)
print(range_of_9)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
fours = np.ones((4, 4))
#make a matrix
print(fours) '''[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]'''

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
#CREATE 5 EVENLY SPACED NUMBERS BETWEEN 0 AND 1 USING np.linspace
linespace = np.linspace(0, 1, 5)
print(linespace)
#Return evenly spaced numbers over a specified interval.
#Returns num evenly spaced samples, calculated over the interval [start, stop].
#The endpoint of the interval can optionally be excluded.

[0.   0.25 0.5  0.75 1.  ]


In [23]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#created a multidimentional array, matrix
#try to print the element at row1 column2
print(mat[0,1])
print("second number from every row", mat[:, 1]) #colon picks up everything in that specific row
#[2 5 8]
print("every row and choose the third number", mat[:, 2])
#[3 6 9]

2
second number from every row [2 5 8]
every row and choose the third number [3 6 9]


In [36]:
'''Create an array of numbers 1–10. Slice out the first 5.
From the matrix above, extract the first two rows.
From the matrix above, extract the bottom-right 2×2 sub-matrix.'''

numbers = np.arange(1, 11)
print(numbers)
print(numbers[:5]) #[1 2 3 4 5]

first_two_rows = mat[:2, :]
print("first two rows", first_two_rows)

bottom_right = mat[1:, 1:]
print("bottom two", bottom_right)


[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
first two rows [[1 2 3]
 [4 5 6]]
bottom two [[5 6]
 [8 9]]


In [37]:
array_6  = np.arange(12)
print(array_6)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
print("shape", array_6.shape) #shape (12,)


shape (12,)


In [41]:
print("dimensions", array_6.ndim) #1dimensional array has dimension 1

dimensions 1


In [40]:
print("size", array_6.size) #12 indexes


size 12


In [45]:
#RESHAPING AN ARRAY
array_7= np.arange(1,13)
print(array_7)
#[ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped = array_7.reshape(3, 4)
print("reshaped", reshaped) #[[ 1  2  3  4]
 #[ 5  6  7  8]
 #[ 9 10 11 12]]

 #we can also flatten the array with RAVEL()
flat = reshaped.ravel()
print("flattened", flat) #back to 1 dimension

[ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
flattened [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [55]:
'''Reshape the array of numbers 1–12 into a 4×3 matrix. <br>
Extract the middle two columns.<br>
Flatten the result into 1D.'''
#1
numbers = np.arange(1, 13)
print(numbers)
#reshape
reshaped_1 = numbers.reshape(4, 3)
print(reshaped_1)

#2
two_middle_columns = reshaped_1[: , 1:3]
print("extract middle 2 colums", two_middle_columns)

#3
flatten_two_columns = two_middle_columns.ravel()
print("flatten", flatten_two_columns)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
extract middle 2 colums [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
flatten [ 2  3  5  6  8  9 11 12]


In [68]:
#ELEMENT OPERATIONS
a = np.array([1,2,3,4])
b=np.array([10,20,30,40])
print(a)
print(b)

#no commas with np array allows us to perform different operations

#ADD both arrays together
print("A + B", a + b) #each index of one array adds with its correspective of the other array
#[11 22 33 44]

#SUBTRACT, MULTIPLY, DIVIDE can also be done
print("a divided by b", a/b) #[0.1 0.1 0.1 0.1]

#SQUARE ROOT
print("square root of a ", np.sqrt(a)) #[1.         1.41421356 1.73205081 2.        ]

#exponential
print("expo of b", np.exp(b)) #[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]

#Create two arrays [5, 10, 15] and [2, 4, 6]. Perform addition, subtraction, multiplication, and division.
#Compute the cube (**3) of the first array.
#1
c = np.array([5,10,15])
print(c)
d = np.array([2,4,6])
print(d)

print("addition", c + d)
print("substraction", c - d)
print("multiplication", c * d)
print("division", c / d)

#2
print("cube root", np.cbrt(c) )
print("cube", c**3)


[1 2 3 4]
[10 20 30 40]
A + B [11 22 33 44]
a divided by b [0.1 0.1 0.1 0.1]
square root of a  [1.         1.41421356 1.73205081 2.        ]
expo of b [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
[ 5 10 15]
[2 4 6]
addition [ 7 14 21]
substraction [3 6 9]
multiplication [10 40 90]
division [2.5 2.5 2.5]
cube root [1.70997595 2.15443469 2.46621207]
cube [ 125 1000 3375]


In [71]:
#BROADCASTING

Broad = np.array([1,2,3,4,5])

print("array plus 10 to each item", Broad + 10)
#it stretches 10 across each item. it creates a new array under the hood
#that is filled with 10s [10,10,10,10,10]
#[11 12 13 14 15]
#same with multiplications and other operations

arr_2d = np.array([[1,2,3], [4,5,6]])
print("full 2 dimensional array", arr_2d)

#I want to add numbers in array 10, 20, 30 to my existing arrays
#10 adds to indexes of first col, 20 adds to second col

print("add the array [10,20,30]", np.array([10,20,30]) + arr_2d)
#[10,20,30] [[11 22 33] [14 25 36]] it stretches the first array out
#creates under the hood [10,20,30][10,20,30]

array plus 10 to each item [11 12 13 14 15]
full 2 dimensional array [[1 2 3]
 [4 5 6]]
add the array [10,20,30] [[11 22 33]
 [14 25 36]]


In [87]:
'''Multiply an array [2, 4, 6, 8] by 0.5.
Create a 3×3 matrix and add np.array([1, 2, 3]) to it.
Create a 2×3 matrix and add 10 to all elements.'''

#1

arr_3 = np.array([2,4,6,8])
print(arr_3)
multiply = arr_3 * 0.5
print("multiply", multiply)

#2

matrix_1 = np.arange(1,10)
print(matrix_1)
reshape_1 = matrix_1.reshape(3,3)
print("reshape", reshape_1)
add_1 = reshape_1 + np.array([1,2,3])
print("add array", add_1)

#3

matrix_2 = np.arange(1,7)
print(matrix_2)
reshape_2 = matrix_2.reshape(2,3)
print("reshape 2x3", reshape_2)
print(reshape_2 + 10 )

[2 4 6 8]
multiply [1. 2. 3. 4.]
[1 2 3 4 5 6 7 8 9]
reshape [[1 2 3]
 [4 5 6]
 [7 8 9]]
add array [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[1 2 3 4 5 6]
reshape 2x3 [[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


In [92]:
import time

#python list compared to numpy array

size = 1_000_000

list_1 = list(range(size))
start = time.time()
list_2 = [x * 2 for x in list_1]
print("Python list time: ", time.time() - start)
numpy_1 = np.arange(size)
start_1 = time.time()
numpy_2 = numpy_1 * 2
print("Numpy array time: ", time.time() - start_1)

#time for python is much longer to compile

Python list time:  0.05670356750488281
Numpy array time:  0.0015110969543457031


In [96]:
#USE RANDOM GENERATOR ON NUMPY
#Random numbers generated from the random will be an example of a dice role

dice = np.random.randint(1,7, size=10)

print("dice rolls", dice)

rand_floats = np.random.rand(5)
print("creates random floats from 0 to 1", rand_floats)

#random normal distribution
rand_dist = np.random.randn(5)
print(rand_dist)


dice rolls [2 5 3 1 6 1 6 6 3 5]
creates random floats from 0 to 1 [0.38697669 0.24538057 0.07200495 0.58261583 0.53348515]
[ 1.03534729 -0.00651276 -0.85704553  0.52291754 -2.72191425]


In [106]:
'''Generate 20 dice rolls and find the min and max.
Create an array of 10 random floats between 0 and 10. - Why do we have to use uniform
Generate 1000 samples from a normal distribution and inspect the first 10.'''

#1
dice_2 = np.random.randint(1,7, size=20)
print("prints 20 random dice rolls that are integer in range 1-6", dice_2)
print("max value", dice_2.max())
print("min value", dice_2.min())

#2
#we have to use uniform otherwise we get floats from 0 to 1
rand_floats_2 = np.random.uniform(low=0.0, high=10.0, size=10)
print("uniform", rand_floats_2)

#3
rand_dist_2 = np.random.randn(1000)
print("sample of 10", rand_dist_2[:10])


prints 20 random dice rolls that are integer in range 1-6 [6 5 6 4 3 2 5 6 5 4 3 1 6 6 1 6 5 3 6 4]
max value 6
min value 1
uniform [4.07780285 6.82033546 3.94852323 2.01785329 4.22532521 1.31059518
 9.68075073 3.58697185 3.61200843 9.03836944]
sample of 10 [ 0.49500911  1.31596778 -1.52075029 -0.62786359 -1.18413724 -1.25534096
  0.6634664   2.60099402 -1.72199117 -1.43072952]


In [111]:
#BASIC STATISTIC
stats_arr = np.array([1,2,3,4,5,6,7,8,9,10])

#sum: sum the whole elements of the array
print("sum", np.sum(stats_arr))

#mean
print("mean", np.mean(stats_arr))

#median
print("median", np.median(stats_arr))

#standard deviation (amount of spread of data)
print("std", np.std(stats_arr))

sum 55
mean 5.5
median 5.5
std 2.8722813232690143


In [123]:
'''Compute statistics for the dice rolls you generated and print them
Create an array of 50 random integers between 10 and 100 and compute mean, median, and standard deviation, print them all out'''

#1
print(dice_2)
print("sum", np.sum(dice_2))
print("mean", np.mean(dice_2))
print("median", np.median(dice_2))
print("std", np.std(dice_2))

#2
randy = np.random.randint(10, 101, 50)
print("rand int", randy)
print("mean", np.mean(randy))
print("median", np.median(randy))
print("standard deviation", np.std(randy)) #approximately 1/4 of current range, in this case 26

[6 5 6 4 3 2 5 6 5 4 3 1 6 6 1 6 5 3 6 4]
sum 87
mean 4.35
median 5.0
std 1.6515144564913746
rand int [ 89  35  87 100  39  39  87  28  35  10  90  16  19  96  78  16  97  88
  44  60  70  37  47  19  43  84  61  27  89  10  59  12  23  89  24  92
  62  34  67  85  37  68  46  30  28  41  43  35  69  81]
mean 53.3
median 45.0
standard deviation 27.664598316259717


In [127]:
#we can stack something vertically and horizontally
stack_1 = np.array([1,2,3])
stack_2=np.array([4,5,6])

vstacked = np.vstack([stack_1, stack_2])
print(vstacked) #[[1 2 3]
# [4 5 6]]

hstacked = np.hstack([stack_1, stack_2])
print(hstacked) #[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [134]:
'''Create a 1D array of 16 random integers and reshape it to 4×4.
Create two new arrays manually using np.array. Stack them two 2×2 arrays both vertically and horizontally.
Generate 2 sets of 5 dice rolls. Stack them into a 2×5 array.'''

#1
arr_1d = np.random.randint(1, 24, 16).reshape(4,4)
print(arr_1d)

#2
manual_1 = np.array([1,2])
manual_2 = np.array([3,4])
v_stack2 = np.vstack([manual_1, manual_2])
print("vertical stack", v_stack2 )
h_stack2 = np.hstack([manual_1, manual_2])
print("horizontal stack", h_stack2)

#3
dice_3 = np.random.randint(1,7,5)
dice_4 = np.random.randint(1,7,5)
v_stack3 = np.vstack([dice_3, dice_4])
h_stack3 =np.hstack([dice_3, dice_4])
print(dice_3, dice_4)
print("vstack", v_stack3)
print("hstack", h_stack3)

[[ 3 22  5 20]
 [ 2  3 14 14]
 [22 16 20  7]
 [20  7  6  8]]
vertical stack [[1 2]
 [3 4]]
horizontal stack [1 2 3 4]
[2 6 1 3 1] [2 3 3 3 3]
vstack [[2 6 1 3 1]
 [2 3 3 3 3]]
hstack [2 6 1 3 1 2 3 3 3 3]
